core/accounts/urls.py
from django.urls import path
from .views import LoginView, RegisterView, logout_view, ProfileView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', logout_view, name='logout'),
    path('profile/<int:pk>', ProfileView.as_view(), name='profile')
]

core/api/urls.py
from django.urls import path
from .views import favorite_api_view

urlpatterns = [
    path('favorite/<int:pk>', favorite_api_view, name='favorite')
]

core/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('auth/', include('accounts.urls')),
    path('', include('gallery.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/gallery/urls.py
from django.urls import path
from .views import (GalleryListView,
                    GalleryCreateView,
                    GalleryUpdateView,
                    GalleryDetailView,
                    GalleryDeleteView)

urlpatterns = [
    path('', GalleryListView.as_view(), name='gallery-list'),
    path('gallery/create', GalleryCreateView.as_view(), name='gallery-create'),
    path('gallery/<int:pk>/update', GalleryUpdateView.as_view(), name='gallery-update'),
    path('gallery/<int:pk>/detail', GalleryDetailView.as_view(), name='gallery-detail'),
    path('gallery/<int:pk>/delete', GalleryDeleteView.as_view(), name='gallery-delete'),
]

core/accounts/models.py
from django.db import models
#
#
# class Account(models.Model):
#     pass

core/api/models.py
from django.db import models

# Create your models here.

core/gallery/models/gallery.py
from django.db import models
from django.contrib.auth import get_user_model


class Gallery(models.Model):
    photo = models.ImageField(
        verbose_name='Картина',
        null=False,
        blank=False,
        upload_to='img'
    )
    signature = models.CharField(
        verbose_name='Подпись',
        null=False,
        blank=False,
    )
    created_at = models.DateTimeField(
        verbose_name='Дата и время создания',
        auto_now_add=True
    )
    author = models.ForeignKey(
        verbose_name='Автор',
        to=get_user_model(),
        null=False,
        blank=False,
        on_delete=models.CASCADE
    )
    favorite = models.ManyToManyField(
        verbose_name='Избранное',
        to=get_user_model(),
        related_name='favorite'
    )

core/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model


class LoginForm(forms.Form):
    username = forms.CharField(max_length=60, required=True, label='Логин')
    password = forms.CharField(max_length=70, required=True, label='Пароль', widget=forms.PasswordInput)


class RegisterForm(forms.ModelForm):
    password = forms.CharField(label='Пароль', required=True, strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='Подтвержение пароля', required=True, strip=False, widget=forms.PasswordInput)
    email = forms.EmailField(required=True, label='Почта')

    class Meta:
        model = get_user_model()
        fields = ('username', 'password', 'password_confirm', 'first_name', 'last_name', 'email')

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

core/gallery/forms.py
from django import forms
from .models import Gallery


class GalleryForm(forms.ModelForm):
    class Meta:
        model = Gallery
        fields = ('photo', 'signature')
        labels = {
            'photo': 'Картина',
            'signature': 'Подпись',
        }

core/accounts/views.py
from django.shortcuts import redirect, reverse
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView
from accounts.forms import LoginForm, RegisterForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model


class LoginView(TemplateView):
    template_name = 'login.html'
    form = LoginForm

    def get(self, request, *args, **kwargs):
        form = self.form()
        context = {'form': form}
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST)
        if not form.is_valid():
            return redirect('/')
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(request, username=username, password=password)
        if not user:
            return redirect('/')
        login(request, user)
        next = request.GET.get('next')
        if next:
            return redirect(next)
        return redirect('/')


def logout_view(request):
    logout(request)
    return redirect('/')


class RegisterView(CreateView):
    template_name = 'register.html'
    form_class = RegisterForm
    success_url = '/'

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(self.success_url)
        context = {'form': form}
        return self.render_to_response(context)


class ProfileView(DetailView):
    model = get_user_model()
    template_name = 'profile.html'
    context_object_name = 'user_obj'

core/api/views.py
from django.shortcuts import render
from gallery.models import Gallery
from django.http import JsonResponse
import json
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt


@csrf_exempt
def favorite_api_view(request, *args, **kwargs):
    if request.method == 'POST':
        user = request.user
        gallery = Gallery.objects.get(pk=kwargs.get('pk'))
        if user not in gallery.favorite.all():
            gallery.favorite.add(user)
        else:
            gallery.favorite.remove(user)
        return JsonResponse({'status': 'ok'})

core/gallery/views.py
from django.shortcuts import render, redirect
from .models import Gallery
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView
from .forms import GalleryForm


class GalleryListView(ListView):
    template_name = 'index.html'
    model = Gallery
    context_object_name = 'galleries'
    paginate_by = 5
    ordering = ('-created_at',)


class GalleryCreateView(CreateView):
    template_name = 'create_gallery.html'
    model = Gallery
    form_class = GalleryForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            gallery = form.save(commit=False)
            gallery.author = self.request.user
            form.save()
            return redirect('/')
        context = {'form': form}
        return self.render_to_response(context)


class GalleryUpdateView(UpdateView):
    template_name = 'gallery_update.html'
    model = Gallery
    form_class = GalleryForm
    success_url = '/'


class GalleryDetailView(DetailView):
    template_name = 'gallery_detail.html'
    model = Gallery
    context_object_name = 'gallery'


class GalleryDeleteView(DeleteView):
    template_name = 'gallery_delete.html'
    model = Gallery
    success_url = '/'

core/accounts/templates/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="container cont">
        <div class="row d-flex justify-content-center">
            <div class="col-7 card text-bg-light form-margins">
                <form method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <div class="form_row">
                        {% bootstrap_button button_type="submit" content='Войти' %}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

core/accounts/templates/profile.html
{% extends 'base.html' %}
{% block title %}Profile{% endblock %}
{% block content %}
    <div class="container cont">
        <div class="row d-flex justify-content-start">
            <div class="col-7 card text-bg-light form-margins">
                <h2>Личная страница {{ user_obj.username }}</h2><br>
                <h4>Логин: {{ user_obj.username }}</h4><br>
                <h4>Почта: {{ user_obj.email }}</h4><br>
                <h4>Имя: {{ user_obj.first_name }}</h4><br>
                <h4>Фамилия: {{ user_obj.last_name }}</h4><br>
            </div>
        </div>
        <br>
        <h3>Избранное</h3><br>
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for i in user_obj.favorite.all %}
                <div class="col">
                    <a href="{% url 'profile' i.author.pk %}"><img src="{{ i.photo.url }}" alt="" height="350"
                                                                   width="350"></a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/accounts/templates/register.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="container cont">
        <div class="row d-flex justify-content-center">
            <div class="col-7 card text-bg-light form-margins">
                <form method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <div class="form_row">
                        {% bootstrap_button button_type="submit" content='Зарегестрироваться' %}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

core/gallery/templates/base.html
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}Title{% endblock %}</title>
</head>
<body>
<nav class="navbar">
    <div class="container">
        <a class="navbar-brand" href="/" style="color: black">Gallery</a>
        <ul class="nav justify-content-end">
            {% block menu %}{% endblock %}
        </ul>
    </div>
</nav>
{% block content %}{% endblock %}
</body>
</html>

core/gallery/templates/create_gallery.html
{% extends 'base.html' %}
{% block title %}Add Gallery{% endblock %}
{% block content %}
    <div class="container cont">
        <div class="row d-flex justify-content-center">
            <div class="col-7 card text-bg-light form-margins">
                <h2>Добавление</h2>
                <form method="post" enctype="multipart/form-data">
                    {% include 'partial/create_or_update.html' with button='Добавить' %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

core/gallery/templates/gallery_delete.html
{% extends 'base.html' %}
{% block title %}Delete Gallery{% endblock %}
{% block content %}
    <div class="container cont">
        <h3>Вы действительно хотите удалить галерею?</h3><br>
        <div class="btn-group" role="group">
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Да</button>
            </form>
            <a href="/">
                <button type="submit" class="btn btn-success" style="margin-left: 10px">Нет</button>
            </a>
        </div>
    </div>
{% endblock %}

core/gallery/templates/gallery_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Detail{% endblock %}
{% block menu %}
    {% if user.is_authenticated %}
        {% if gallery.author == request.user or perms.gallery.change_gallery %}
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'gallery-update' gallery.pk %}">
                    <button type="button" class="btn btn-dark">Редактировать</button>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'gallery-delete' gallery.pk %}">
                    <button type="button" class="btn btn-dark">Удалить</button>
                </a>
            </li>
        {% endif %}
    {% endif %}
{% endblock %}
{% block content %}
    <div class="container cont">
        <div class="card" style="max-width: 100%;">
            <div class="row g-0">
                <div class="col-md-4">
                    {% if gallery.photo %}
                        <img src="{{ gallery.photo.url }}" class="img-fluid rounded-start"
                             alt="{{ gallery.photo.url }}">
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">Автор - <a class="profile"
                                                          href="{% url 'profile' gallery.author.pk %}">{{ gallery.author }}</a>
                        </h5><br>
                        <h5 class="card-title">Подпись - {{ gallery.signature }}</h5><br>
                        <h5 class="card-title">Создание - {{ gallery.created_at }}</h5><br>
                        <a class="nav-link" aria-current="page" href="/">
                            <button type="button" class="btn btn-dark">Назад</button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

core/gallery/templates/gallery_update.html
{% extends 'base.html' %}
{% block title %}Update Gallery{% endblock %}
{% block content %}
    <div class="container cont">
        <div class="row d-flex justify-content-center">
            <div class="col-7 card text-bg-light form-margins">
                <h2>Редактирование</h2>
                <form method="post" enctype="multipart/form-data">
                    {% include 'partial/create_or_update.html' with button='Редактировать' %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

core/gallery/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Galleries{% endblock %}
{% block menu %}
    {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'logout' %}">
                <button type="button" class="btn btn-dark">Выйти</button>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'gallery-create' %}">
                <button type="button" class="btn btn-dark">Добавить</button>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'profile' request.user.pk %}">
                <button type="button" class="btn btn-dark">Кабинет</button>
            </a>
        </li>
    {% else %}
        <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'login' %}">
                <button type="button" class="btn btn-dark">Войти</button>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'register' %}">
                <button type="button" class="btn btn-dark">Зарегестрироваться</button>
            </a>
        </li>
    {% endif %}
{% endblock %}
{% block content %}
    <div class="container cont">
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for gallery in galleries %}
                <div class="col">
                    <div class="card">
                        {% if gallery.photo %}
                            <img src="{{ gallery.photo.url }}" class="card-img-top" alt="{{ gallery.photo.url }}">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">Автор:{% if user.is_authenticated %} <a class="profile"
                                                                                           href="{% url 'profile' gallery.author.pk %}">{{ gallery.author }}</a>{% else %}
                                {{ gallery.author }}{% endif %}
                            </h5>
                            <h5 class="card-title">Подпись: {{ gallery.signature }}</h5><br>
                            <div class="btn-group" role="group">
                                <a class="nav-link" aria-current="page" href="{% url 'gallery-detail' gallery.pk %}">
                                    <button type="button" class="btn btn-dark">Подробнее</button>
                                </a>
                                {% if user.is_authenticated %}
                                    <input type="submit" class="btn btn-success"
                                           id="{{ gallery.pk }}" value="Добавить"
                                           style="margin-left: 10px; border-radius: 5px">
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <br>
        {% include 'partial/pagination.html' %}
    </div>
    <script type="application/javascript">
        const add = document.querySelectorAll('.btn-success');
        add.forEach(add => add.addEventListener('click', function () {
            let xhr = new XMLHttpRequest();
            xhr.onload = function () {
                console.log(xhr.status);
            };
            if (add.value === 'Добавить') {
                add.value = 'Удалить'
            } else {
                add.value = 'Добавить'
            }
            xhr.open('POST', `api/favorite/${this.getAttribute('id')}`);
            xhr.send()
        }))
    </script>
{% endblock %}

core/gallery/templates/partial/create_or_update.html
{% csrf_token %}
{% load django_bootstrap5 %}
{% bootstrap_form form %}
<input type="submit" class="btn btn-success" value="{{ button }}">

core/gallery/templates/partial/pagination.html
<div class="container">
    <div class="pagination">
    <span class="step-links">
        <a href="?page=1">В начало</a>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Назад</a>
        {% else %}
            <span class="page-disabled">Назад</span>
        {% endif %}
        <form class="current-page" method="get">
            <label for="page">
                <input type="hidden" name="search" value="{{ search }}">
                Страница <input type="text" name="page" id="page" value="{{ page_obj.number }}">
                из {{ page_obj.paginator.num_pages }}.
            </label>
        </form>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Далее</a>
        {% else %}
            <span class="page-disabled">Далее</span>
        {% endif %}
        <a href="?page={{ page_obj.paginator.num_pages }}">В конец &raquo;</a>
    </span>
    </div>
</div>